
version: "3"

services:
  mongo:    
    image: mongo
    ports:
      - "27017:27017"
  
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo

  app:
    image: lucascarrafa/server_snmp:1.2
    links:
      - mongo
    ports:
      - "5000:5000"
    depends_on:
      - mongo
